# Site settings
title: Xander Miller
email: xander.miller@gmail.com
url: https://pareidoliax.github.io
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
skills: "Rails Developer - Bloc Mentor - Data Science Samurai"
meta_author: Miller Xander

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
#Â - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 00ADEF #80B3FF
  primary-rgb: "0,173,239" #"128,179,255"
  secondary: F17B34  #FD6E8A
  secondary-dark: BC350C #A2122F

# Footer settings
footer:
  copyright: Xander Miller
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/PareidoliaX
  - title: facebook
    url: https://www.facebook.com/xander.miller
  - title: stack-overflow
    url: http://stackoverflow.com/users/2364401/pareidoliax
  - title: bitbucket
    url: https://bitbucket.org/pareidoliax/
  - title: github
    url: https://github.com/PareidoliaX

# Postal address (add as many lines as necessary)
address:
  - line: 'Ottawa, Canada'

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
